### ISSUE TITLE
SDC-pepolar implementation fails for some participants

### ISSUE THREAD

**Issue by markushs** [nipreps/sdcflows#10]
Hi,

The SDC-pepolar implementation in fmriprep (1.3.1) has worked fine for most subjects in a dataset we are acquiring. However, for a few, typically older, participants we see very strange results. Interestingly, the spin-echo EPIs with opposing phase encoding (AP/PA) used to estimate fieldmaps also look somewhat strange in the failing participants.

Examples of SE EPIs in a subject that is handled well by fmriprep:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44242647/54423207-6a4d2400-4710-11e9-9733-575dee033696.png">

SDC results for this subject in fmriprep
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44242647/54424040-54d8f980-4712-11e9-92e5-90923ff08be0.png">

Examples of SE EPIs in a subject that is *not* handled well by fmriprep:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44242647/54424162-99fd2b80-4712-11e9-8ff4-e41d83e0e82b.png">

And the resulting SDC output (note especially how anterior parts of lateral ventricle / corpus callosum get compressed; x = -17)
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44242647/54423854-ea27be00-4711-11e9-855a-a8d9ea2ff1b4.png">

The reason I report this as an issue here (and not as an open question on neurostars) is because these subjects – with "non-prototypical" blip-up/blip-down-images – are handled well when using topup+applytopup to estimate and applying the fieldmap (i.e., the resulting distortion-corrected GRE EPIs align well with the structural scan).

Topup-estimated fieldmap from the second set of SE EPIs shown above (GRE EPI BOLD data with PE-direction AP to the left):
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44242647/54435971-fa4f9580-4731-11e9-8174-ef57851c0f0c.png">

Distortion-corrected GRE EPI (applytopup) coregistered with structural T1w (WM-edge from FSL FAST overlaid). Same data as in the second SDC output shown above.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44242647/54434716-2ddcf080-472f-11e9-8d14-bf0e72272d79.png">

I'm wondering if this issue could be related to the limiting of displacement estimation to the target file phase encoding direction (as stated in the documentation for `fmriprep.workflows.fieldmap.pepolar.init_pepolar_unwarp_wf`). Clearly, in the second set of SE EPIs shown above, some displacements seem to go in the opposite direction of the phase encoding direction. Why this is happening for some subjects, I don't know, but as I wrote initially it seems to be the case mostly for older adults. I have verified that all scanner parameters and .json-info were correct for the relevant scans. Moreover, the "strange" PE-direction effects in some subjects seem to be stable across scanner sessions (we collect several fieldmaps over several days for these participants).

Thanks!
Markus

**Comment by markushs** [comment]
Hi!
I just wanted to follow up on this one. We keep having problems with the SDC-pepolar step in fmriprep/sdcflows. I am quite convinced that the problem does not lie in our data, as a FSL topup-approach to distortion correction produce nice-looking functionals after SDC.

Here's an example:

SDC performed using FSL topup + applytopup (Freesurfer's white surface in green)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/65770880-4ba3fd00-e137-11e9-9a07-58074954bb2a.png">

SDC performed using 3dQwarp+ANTs (through fmriprep v.1.4.0). Compare e.g. the rostral Anterior Cingulates
<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/65770951-72623380-e137-11e9-8a41-665eb068e1e9.png">

Another example:

FSL topup:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/65773609-e9e69180-e13c-11e9-97f2-20b0c660286b.png">

3dQwarp+ANTs:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/44242647/65773660-fc60cb00-e13c-11e9-976c-68022d17c334.png">

We see this issue – "overcompressed" frontal lobes following fmriprep's SDC – all the time, and also with participants with "normal-looking" Spin-echo-EPIs of (i.e., the problem is not limited to the "strange" cases reported in the original post). As mentioned originally, however, topup seems to deal nicely also with the strange cases.

Here's the code used to do the comparison (note that topup is starting with the same input as sdcflows):

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/44242647/65775954-6d09e680-e141-11e9-8145-db6df397b108.png">


So the question, I guess, is whether it's possible to incorporate a topup-option in SDCflows, or if you have any ideas for a workaround to ensure good correspondence between functionals and structurals in our case? I should mention that we are collecting data with the HCP/CMRR-multiband-sequence with MB=4 but no acceleration beyond that. So the geometric distortions in the phase-encoding direction (A-->P) are quite strong, and similar to what is seen with HCP-data from the Prisma in general.

Thanks!

**Comment by oesteban** [comment]
Hi @markushs, your request is totally reasonable. There is no topup option for historical reasons, and we should bring it in - can you open an issue explicitly requesting it?

We will also look into ``3dQWarp`` and check what regularization options are there to help alleviate these problems.

**Comment by markushs** [comment]
Thanks, @oesteban. 
Sure, I'll open a new issue.
