### ISSUE TITLE
> Question-- do the reports need to visualize the inhomogeneity outside of the brain or do you think we should just mask it so that users don't get alarmed by the amount of out-of-brain field inhomogeneity?

### ISSUE THREAD

**Issue by dPys** [nipreps/sdcflows#105]
> Question-- do the reports need to visualize the inhomogeneity outside of the brain or do you think we should just mask it so that users don't get alarmed by the amount of out-of-brain field inhomogeneity?

This question is THE QUESTION. On the one hand, I do agree it is alarming (especially to the non-familiar eye). On the other hand, I think it is nice to compare how different methods regularize outside the brain differently. For instance, the traditional FUGUE correction (the infamous `epiunwarp.fsl` script) extrapolates (constant) the values at brain edges along the PE axis. That produces [this kind of "rays"](https://neurostars.org/t/fmriprep-fieldmap/6000):
![Screen Shot 2020-02-06 at 2 17 52 PM (1)](https://user-images.githubusercontent.com/598470/84087697-8d13ca00-a99f-11ea-9d20-cc6b18c3619a.jpg)

Would you mind filing an issue about this at [SDCflows](https://github.com/nipreps/sdcflows/issues/new)?

_Originally posted by @oesteban in https://github.com/nipreps/dmriprep/pull/97#issuecomment-640927659_

**Comment by oesteban** [comment]
We have made two important changes:
- #120 - which makes these "rays" to be plotted always aligned with the PE axis (which is less confusing)
- #119 - which extrapolates the field outside using B-Splines basis (i.e., no more weird rays anymore)

Closing as this has been addressed.
