### ISSUE TITLE
Inverted 3dQwarp SDC in OFC

### ISSUE THREAD

**Issue by jmtyszka** [nipreps/sdcflows#117]
I'm seeing the 3dQwarp-based SDC in FMRIPREP try to fill an area of dropout in posterior OFC with signal from anterior OFC when using SE-EPI polarity reversed pairs for fieldmap estimation. This happens fairly consistently and doesn't happen with TOPUP SDC estimation outside of fmriprep/sdcflows. Not sure if this is an issue with high levels of distortion in the SE-EPI pair at higher spatial resolutions (longer EPI echo trains). In our case, we see this effect at 2 mm isotropic with inplane GRAPPA 2.

Cross-posted with images posted to [NeuroStars](https://neurostars.org/t/fmriprep-distortion-correction-issues-with-higher-resolution-mb-epi/17307)

**Comment by effigies** [comment]
Just want to link https://github.com/nipreps/fmriprep/issues/2210. You're right that 3dQwarp does not seem to handle some of these cases well, and I think @oesteban came to a similar conclusion that higher frequency distortions are not well estimated.

**Comment by jmtyszka** [comment]
Thanks @effigies - sorry I didn't spot #2210 earlier. Sounds like adding a TOPUP SDC option to sdcflow is the way to go at this point.

**Comment by effigies** [comment]
Yeah, I think so.
