### ISSUE TITLE
PhaseDiff SDC: phase1/phase2 implementation

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#15]
Based on the foundations set by poldracklab/fmriprep#1359, finish up the phase1/2 implementation.

**Comment by mattcieslak** [comment]
#30 follows up on the suggestions in poldracklab/fmriprep#1359 to switch to the official prelude approach instead of using arctan2. The end result is the same, but now the workflow is consistent with the documentation

**Comment by soichih** [comment]
@oesteban which version of fmriprep support phase1/2 type of fieldmap? I am testing it with 1.5.2 but it looks like it doesn't handle it (yet).

```
	 Found phase1/2 type of fieldmaps, which are not currently supported. fMRIPrep will discard them for susceptibility distortion correction. Please, follow up on this issue at https://github.com/poldracklab/fmriprep/issues/1655.
191223-13:56:29,758 nipype.workflow IMPORTANT:
```

**Comment by oesteban** [comment]
We integrated the new fieldmaps in 1.5.3 - https://github.com/poldracklab/fmriprep/releases/tag/1.5.3

**Comment by soichih** [comment]
I tried 1.5.3 (and 1.5.4) but I couldn't get it to work for us... https://github.com/poldracklab/fmriprep/issues/1921

I will stay with 1.5.2 for now.
