### ISSUE TITLE
PE-Polar SDC: Unify interface

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#18]
Currently, two important inputs are passed by argument (`bold_meta`, and `epi_fmaps`) and the other three (`in_reference`, `in_reference_brain`, `in_mask`) are passed by Nipype workflow inputs.

All of them should be workflow inputs.

**Comment by mattcieslak** [comment]
Any thoughts on replacing `bold` with `distorted` and `undistorted`? A number of interfaces have `bold_ref` as both inputs and outputs. It might make sense to have inputs be `distorted_ref` and outputs be `undistorted_ref`. The boilerplate is also specific to bold, which is confusing when it's included in the html for preprocessed dwi data.

**Comment by effigies** [comment]
@mattcieslak Perhaps open the bold -> (un)distorted issue separately? This got closed, but the closing PR didn't seem to address it.

**Comment by oesteban** [comment]
Sorry for closing it, I thought it wasn't going to happen.

Yes, please open a new issue - I did not fully removed the term "bold" from the workflow because it'll take deeper changes to replace the enhance&skullstrip workflow with an equivalent with low b images.
