### ISSUE TITLE
T1w-SyN: Is contrast inversion really necessary? (at least for mutual-information scales)

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#187]
I think I've heard @mattcieslak asking about this, please let me know if I'm wrong (whether you made the comment and/or the content of the comment).

The question is that, most of the linear and nonlinear registration steps of our SyN implementation use Mattes. With this cost function, the contrast inversion just does nothing - while it is one more massaging step where we can harm the reliability of the overall process.

Maybe we could limit the contrast inversion only for the final CC ``antsRegistration`` step.

For the case of BOLD, it would be doubtful we need to invert the contrast at all in some cases. Because we are picking the frames with the strongest T1 contrast across all runs in the session with share shimming settings, the inversion is probably not needed anymore (even for the CC metric).

Thoughts?

(I'm giving this very low priority, but nonetheless noting it down for future reference)

EDIT: I just found the comment from Matt - https://github.com/nipreps/sdcflows/issues/68#issuecomment-562805659. It was right under my nose. Apologies.

**Comment by oesteban** [comment]
Related: #68.

**Comment by effigies** [comment]
That sounds correct, but worth verifying with some before/after shots of the specific steps.
