### ISSUE TITLE
[SDC-SyN] Generate a fieldmap template on MNI152NLin2009cAsym space to replace current prior

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#2]
Calculate a new fieldmap average pooling datasets from OpenNeuro that have either fieldmaps or PEPOLAR acquisitions.

The fieldmap average should NOT be masked within the brain.

Then, upload the average to TemplateFlow and remove the old atlas.

**Comment by mattcieslak** [comment]
Would it make sense to also include fieldmaps from pepolar b=0 acquisitions? We could get many of these from HCP or ABCD.

**Comment by oesteban** [comment]
Update: this seems still pertinent, and we could ensure smoothness by averaging B-Spline coefficients (which is a lot less data, and do not need interpolation when mapping on to the target space because they are kept on the same grid). If we generate this template (edited the title of the issue for appropriateness), then we will be able to remove one transformation hop (and hence a potential point of failure) here https://github.com/nipreps/sdcflows/blob/aa1ff974429d245c8c7f76f886f7de27e8650865/sdcflows/workflows/fit/syn.py#L156-L161.

> @mattcieslak 
> Would it make sense to also include fieldmaps from pepolar b=0 acquisitions? We could get many of these from HCP or ABCD.

That would be convenient for dMRIPrep in general, the same way we generated a "boldref" template for fMRIPrep a while ago. I'll open an issue there.

In the context of this PR, the idea is to create an average of fieldmaps (i.e., to get a sense of where most of the distortion is happening).

**Comment by mattcieslak** [comment]
Is there also a source of GRE fieldmaps? We're finding that the pepolar fieldmaps don't match very well with GRE fieldmaps even with the same shim settings

**Comment by oesteban** [comment]
> We're finding that the pepolar fieldmaps don't match very well with GRE fieldmaps even with the same shim settings

This is not surprising - the smoothing/despiking of GRE fieldmaps make them "underfit", however PEPOLAR fieldmaps tend to overfit, actually.

With the work towards 1.4.0, we'll be able to regularize both GRE and PEPOLAR fieldmaps with B-Splines and bring them closer to one another.

That said, I think for this average we can pool in both types of fieldmap.

**Comment by oesteban** [comment]
This doesn't seem like a current need - please correct me if I'm wrong, @effigies (and reopen)

**Comment by mattcieslak** [comment]
> This is not surprising - the smoothing/despiking of GRE fieldmaps make them "underfit", however PEPOLAR fieldmaps tend to overfit, actually.
> 

The differences were fairly big. For example the entire OFC would be displaced in opposite directions in the SyN SDC and B0 fieldmap estimates. In our experiment the B0 and PEPOLAR always had the same direction of displacements but minor differences in the displacement distance.
