### ISSUE TITLE
Integrate SDC into ``init_epi_reference_wf``

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#208]
Continuing with the vision of nipreps/niworkflows#601, and on top of the first prototype (nipreps/niworkflows#610), this issue is a feature request to provide *distortion-free* EPI references.

**Comment by oesteban** [comment]
Instead of risking bijective dependencies, the best way forward is to implement this reference workflow here in *SDCflows* directly. Objections?

**Comment by effigies** [comment]
Is this still something you want to do? I looked back at the referenced issue, and it seems we may need to think about whether to revive that effort and how more recent work affects it.

**Comment by oesteban** [comment]
I don't think this makes sense anymore, at least as stated in the title.

- We need good EPI references to feed into topup, but how we calculate them (before SDC) is something that arguable would be done in SDCFlows, or otherwise, SDCFlows should clearly define in its API what the expectation for EPI references is. If finally done internally (and the API just asks for "fieldmappable" EPIs, like right now), I don't think these references need to be exposed.
- Once SDCFlows resamples properly, references for downstream processing can be calculated elsewhere.
