### ISSUE TITLE
BUG: Unwarp workflow generates a fieldmap (3D, in Hz), but it doesn't generate a displacements field map (5D, mm)

### ISSUE THREAD

**Issue by JessyD** [nipreps/sdcflows#219]
Hi, 

As I mentioned on my previous neurostars post (https://neurostars.org/t/sdcflows-applytopup/19516), I am trying to use sdcflows to correct a BOLD image before applying fMRIPrep to it. Following our last discussion, I have run fMRIPrep to obtain only the slicetime and motion correction. The command I used was the following:
```
singularity run --cleanenv                                                      \
	-B ${TEMPLATEFLOW_HOST_HOME}:${SINGULARITYENV_TEMPLATEFLOW_HOME}            \
	-B /data/HCP/hcp_test_bids:/in                                              \
	-B ${TMPDIR}/out:/out                                                       \
	-B ${TMPDIR}/wrk:/wrk                                                       \
	${container} /in /out/${s} participant                                      \
	--participant_label ${s}                                                    \
	-w /wrk/${s}                                                                \
	--nthreads 4 		                                                    \
	--mem_mb 48000                                                              \
	--fs-license-file ${license}                                                \
	--fs-no-reconall     	 						    \
	--skip-bids-validation                                                      \
	--notrack                                                                   \
	--ignore fieldmaps 					                    \
	--omp-nthreads 3   
```
The output looks like this
<img width="1609" alt="simple_fmri" src="https://user-images.githubusercontent.com/10345440/128078517-a4008074-8a0b-4460-944a-d9d72334ee23.png">

I have also created this script to merge the transformations obtained from sdcflows, the motion correction parameters, and transform the EPI image. 
You can see the script I used to merge the transformations here (https://github.com/JessyD/sdcflows-test/blob/master/apply_sdcflows.py). However, the outputs do not look like what I expected. I tried all permutations on the way that the transformations are passed to `merge_xforms`, but they all look similar to the images below:
- affine --> motion correction --> fieldwarp, 
<img width="1606" alt="2_3_1" src="https://user-images.githubusercontent.com/10345440/128078602-59f68c58-1e4a-49ee-9cb4-d31f0c9eaee1.png">
- motion correction --> affine --> fieldwarp
<img width="1604" alt="3_2_1" src="https://user-images.githubusercontent.com/10345440/128078603-71012717-e245-45e2-97ea-dddfcfdf063f.png">

 Am I missing something or maybe passing the incorrect transformations (https://github.com/JessyD/sdcflows-test/blob/master/apply_sdcflows.py)?

@effigies @mgxd 
Thank you!

**Comment by oesteban** [comment]
I think this is a problem - I'm still trying to fully diagnose it but it looks like a bug indeed.

(EDIT) BTW - this is the issue holding up nipreps/fmriprep#2392

**Comment by oesteban** [comment]
Okay, I've managed to diagnose the issue. The `fieldmap` output from the unwarping workflow is indeed a fieldmap (therefore, just a 3D file, in Hz units).

In order to feed this into `antsApplyTransforms` and generate an actual unwarping transform, the fieldmap needs to be converted (which means, it needs to be set in the right dimensions and scale it by the readout time and pixel size along PE).

Working on a fix now.
