### ISSUE TITLE
ENH: Optional workflow to write warpings out to ``derivatives/sub-ID/fmap/``

### ISSUE THREAD

**Issue by mattcieslak** [nipreps/sdcflows#26]
Would it make sense to add the SDC warp in the derivatives for each unwarped image? At the moment we are saving the entire working directory to keep them. They're also not included in the h5 transform to the template because they differ for each scan. What do you think?

**Comment by effigies** [comment]
In general, I would say if people are digging through the working directory to find something that's not easily generated from other derivatives, it's probably worth having as a derivative.

**Comment by oesteban** [comment]
This should be covered with the super-fancy X5 format. Sadly I am very slow with the implementation :(

**Comment by effigies** [comment]
But we do have the warps, right? I don't think we need to have the final version ready before we provide the derivatives.

**Comment by oesteban** [comment]
Let's make an optional hook to the fieldmap estimation workflows to write out these files while we build the X5 transforms file.

**Comment by oesteban** [comment]
Okay, I'd like to take my previous comments back and push for this. However, I'd like to modify the original intent of @mattcieslak a little bit:

Under the `fmap/` folder you'd find an actual field map in Hertz, after all the curation process (i.e., estimation, smoothing/cleanup, and extrapolation). So we are not talking about warpings - just the field inhomogeneity map.

I would extend this issue to sending a PR to the imaging-general-derivatives in BIDS to describe the naming of this fieldmap (we could keep the fieldmap suffix, I believe), and enforce the units and allowing for some "IntendedFor" field? (will need to think more about this).

Calculating warpings then should be fairly straightforward: you have the field in Hz and you need to read the EffectiveEchoSpacing and PhaseEncodingDirection of your EPI dataset(s) to properly calculate the warp field.
