### ISSUE TITLE
create fieldcoef image 

### ISSUE THREAD

**Issue by mattcieslak** [nipreps/sdcflows#3]
I saw that fmriprep used to have a workflow for creating the fieldcoef files that are now supported by eddy. Do you know if that code still works? Should we add it to this repository?

**Comment by oesteban** [comment]
Where's that code? Isn't it here already?

**Comment by mattcieslak** [comment]
I was wrong about what I thought eddy is expecting. They want a fieldmap scaled in Hz: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--field.  This could be created using `sdcflows.interfaces.fmap.FieldmapToHz` with `range_hz=1` and `in_file` the rads/sec image?

**Comment by mattcieslak** [comment]
I tried it and can confirm that it works. This is really great.

**Comment by oesteban** [comment]
Can you close this issue if it is fixed?
