### ISSUE TITLE
Identify, implement and test the different interactions of PE and EPI's x-forms

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#31]
Comes from https://github.com/poldracklab/fmriprep/issues/1493#issuecomment-459851011

**Comment by oesteban** [comment]
I'm going to push this away until we find a dataset for this. 

cc/ @neurolabusc: I know of your excel table for Philips - can you point us to resources we can leverage to set up some unit-tests for this? I believe the idea was to ensure we always get the PE direction right, in combination with as many possible different orientation headers of the NIfTI.

**Comment by neurolabusc** [comment]
@oesteban the `Missing Information`  section of the [dcm2niix Philips notes](https://github.com/rordenlab/dcm2niix/tree/master/Philips) reveals that current Philips DICOM images do not allow us to determine phase encoding polarity or slice timing. This is a limitation of the Philips DICOMs, not of any converter. 

You may find the validation datasets [dcm_qa_philips](https://github.com/neurolabusc/dcm_qa_philips) and [dcm_qa_enh](https://github.com/neurolabusc/dcm_qa_enh) useful.

**Comment by oesteban** [comment]
Okay I think this is virtually a duplicate of #201. I'm going to merge that issue into this one.

**Comment by oesteban** [comment]
I have edited the title, and will reproduce here the description of the other issue:

First identified in debugging nipreps/nibabies#55, SDCFlows might not be generating correct displacements fields out of fieldmaps (``Coefficients2Warp`` interface) when there are swapped axis and/or flipped directions.

Heavily related to the PR and corresponding conversation taking place in #199.

Both the original writing of this issue and the posterior issue address the same problem of how the PE direction stated in the JSON file affects the actual correction. Therefore, it's not about the conversion to NIfTI, but rather ensuring the interpretation of the PE and how that applies to the actual array of displacements.
