### ISSUE TITLE
SDC-pepolar: topup implementation

### ISSUE THREAD

**Issue by markushs** [nipreps/sdcflows#37]
Follow-up on the suggestion in https://github.com/poldracklab/sdcflows/issues/10 to consider FSL topup as an alternative to 3dQwarp for estimating a displacement field from pairs of EPIs with opposite phase encoding directions.

I'm more than willing to help here, but could need some advice on how to transform the topup output into an ANTs-compatible warp field.

**Comment by markushs** [comment]
Hi @oesteban et al 
This issue keeps occurring with our data , so I'm trying to come up with a temporary fix that I can bind into our singularity image of fMRIPrep (and perhaps inform a future PR). I was wondering whether you see any obvious problems in adapting the Fieldmap workflow (`fmap_wf`) so that it is initiated with topup? The topup estimated fieldmap (in Hz) would then be converted to rad/s and fed into Prelude (and then go through the remaining steps in `fmap_wf` + `sdc_unwarp_wf`).

The required magnitude image would simply be the unwarped (spin-echo) epis from topup.

**Comment by oesteban** [comment]
Recent evidence suggesting we should go for TOPUP: https://doi.org/10.3389/fninf.2019.00076
