### ISSUE TITLE
Do not depend on FreeSurfer

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#46]
FreeSurfer is a heavy dependency and we are just using it for `mri_robust_template` here:

https://github.com/poldracklab/sdcflows/blob/5b4cc23200b6bd6579fc9d1a88856c2e1ef275b2/sdcflows/workflows/pepolar.py#L227-L272

The idea would be to replace that with ANTs' tools.

**Comment by effigies** [comment]
It's a really good tool. Can we not try to have a minimal install that includes it, e.g. a single, statically-linked binary?

**Comment by oesteban** [comment]
I'd be fine with it although I'm more familiar with ANTs and tend to prefer the latter for image registration.

**Comment by mattcieslak** [comment]
The antsMultivariateTemplateConstruction scripts are very similar to mri_robust_template if you set them to run with only rigid or affine registration. It would be great for longitudinal studies spanning many years to have a nonlinear option for making a single-subject template. Would you be interested in a PR on smriprep adding an interface for this?

**Comment by oesteban** [comment]
> The antsMultivariateTemplateConstruction scripts are very similar to mri_robust_template if you set them to run with only rigid or affine registration.

I honestly feel ``mri_robust_template`` is already an overkill for the particular use we're giving it, but yes, I'd be fine switching to ``antsMultivariateTemplateConstruction``. However, it seems easier to do what Chris suggested above (i.e., packing just the necessary binaries not the whole FS).

> It would be great for longitudinal studies spanning many years to have a nonlinear option for making a single-subject template. Would you be interested in a PR on smriprep adding an interface for this?

@rciric was working on a Nipype version of ``antsMultivariateTemplateConstruction``, although I see that development completely unrelated to the problem at hand here.

If the interface is missing in Nipype (Rastko is porting the workflow, not just interfacing), it'd be great for you to send a PR there 👍

**Comment by mattcieslak** [comment]
Hi @rciric! I have ported that workflow to nipype already: https://github.com/PennBBL/qsiprep/blob/master/qsiprep/workflows/dwi/intramodal_template.py#L133 but there is a step in shapeupdatetotemplate that I can't get to work outside of their script (where a temporary file gets overwritten). Have you had any better luck? Also the interface for antsRegistration has to be updated to do a truly multivariate template construction.
