### ISSUE TITLE
Details about phase1/2 fieldmaps - order of operations (subtraction/PRELUDE)

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#59]
Follow the conversation that started around here https://github.com/poldracklab/sdcflows/pull/30#issuecomment-555437926.

**Comment by kimsin98** [comment]
As I explained in https://github.com/poldracklab/sdcflows/pull/30#issuecomment-555881469 , subtracting before unwrapping should result in the same results most of the time and fix cases that produce the out-of-phase "blobs" currently.

I opened a PR with the switch. https://github.com/poldracklab/sdcflows/pull/70
