### ISSUE TITLE
Cleaner edges when unwrapping with just extracted magnitude (no mask)

### ISSUE THREAD

**Issue by kimsin98** [nipreps/sdcflows#71]
I do not understand the reason yet, but fieldmap edges are consistently cleaner when PRELUDE is ran without a mask.

The reason could be because PRELUDE expects either
1. Original magnitude + mask
2. Brain extracted magnitude

but the current workflow provides both.

As of now, the unwrapping sometimes has too much noise on edges that the edge cleaning postprocessing is not enough.

**Comment by AKSoo** [comment]
I checked PRELUDE's source code, and the reason seems to be that without mask, it generates a mask that further filters out some outlier values (below p2 + 0.1(p98 - p2) where p2 and p98 are 2nd/98th percentiles).

Unless the field of view is insanely tight, I don't think applying that threshold would cause any harm, and edges always look cleaner with it.

**Comment by kimsin98** [comment]
I checked PRELUDE's code. Without mask, it generates a mask by filtering outliers values below `p2 + 0.1 * (p98 - p2)` where p2, p98 are 2nd, 98th percentiles (as described in [original article](https://doi.org/10.1002/mrm.10354)). On brain extracted magnitude images, this results in slightly tighter mask. There is no hard theory behind this threshold, but as the authors describe, it seems to give good results with PRELUDE in general.

I don't think applying this threshold would hurt unless the field of view is insanely tight.

Of course, a more sophisticated method for generating the mask could make this irrelevant. But until #23 is addressed, this should help.

**Comment by oesteban** [comment]
I think this is not an issue anymore after #119 - I consistently see that edges do not bias the B-Spline estimation and noise in them is correctly removed. Please reopen if there is some other benefit to letting PRELUDE calculate the mask based on percentiles, but I'd say that in the context of #119 you would prefer to keep a more liberal mask.
