### ISSUE TITLE
Migration to github.com/nipreps

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#86]
Voices against moving this project away from the poldracklab organization?

cc/ @mattcieslak @effigies @mgxd @poldrack

**Comment by effigies** [comment]
I'm happy to move it into a larger community space and signal as less of an in-house project.

**Comment by poldrack** [comment]
+1 for moving to a community organization

**Comment by oesteban** [comment]
Done

**Comment by effigies** [comment]
Circle working?

**Comment by oesteban** [comment]
Looks like so https://circleci.com/gh/nipreps/sdcflows
