### ISSUE TITLE
question: using local docker repository as a cache on circleci

### ISSUE THREAD

**Issue by mattcieslak** [nipreps/sdcflows#87]
Not really an issue, but I noticed this repository isn't using `docker load` and `docker save` like fmriprep does on circleci. Have you noticed an improvement in CI run times? Would your local registry method work for much larger images?

**Comment by effigies** [comment]
My impression is that it's sped things up a bit, but I didn't make any systematic comparison.

**Comment by oesteban** [comment]
Roughly a 30% cheaper. Will propagate the model to fMRIPrep ASAP.

**Comment by mattcieslak** [comment]
thanks, I will try this out too
