### ISSUE TITLE
Double-check effective echo spacing of Philips scans

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#9]
As per https://github.com/poldracklab/fmriprep/pull/1489#issuecomment-461403607, we need to make sure whether it is okay not to take in-plane acceleration into account here:

https://github.com/poldracklab/fmriprep/blob/a255683b2f2a0d643accfb13b341cbd9311cda55/fmriprep/interfaces/fmap.py#L431

Also consider https://github.com/poldracklab/fmriprep/issues/1029#issuecomment-459160935

**Comment by effigies** [comment]
Related to https://github.com/poldracklab/sdcflows/issues/5#issuecomment-585811005, I have Philips that absolutely does not work with current `get_ees`.

**Comment by oesteban** [comment]
Duplicate of #5 - will follow up there.
