### ISSUE TITLE
[MAINT] Docker release deployment

### ISSUE THREAD

**Issue by mgxd** [nipreps/sdcflows#92]
https://circleci.com/gh/nipreps/sdcflows/964?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If we plan on migrating the image host from `r/poldracklab/sdcflows` to  `r/nipreps/sdcflows`, we'll have to extend / change circle's permissions.

**Comment by oesteban** [comment]
Done
