### ISSUE TITLE
remove enhance_and_skullstrip_bold from init_sdc_unwarp_wf?

### ISSUE THREAD

**Issue by mattcieslak** [nipreps/sdcflows#93]
I'm switching qsiprep to use sdcflows and was wondering how everyone would feel about removing the call to `init_enhance_and_skullstrip_bold_wf` from `init_sdc_unwarp_wf`. This function doesn't work well on b=0 images. If sdcflows is going to be modality-agnostic this would be very useful.

**Comment by oesteban** [comment]
I think you're right, this is more than desirable, it's clearly necessary. Happy to help push a quick PR
