### ISSUE TITLE
Report figure inconsistencies

### ISSUE THREAD

**Issue by mgxd** [nipreps/sdcflows#94]
Relevant posts:
https://neurostars.org/t/fmriprep-fieldmap/6000
https://neurostars.org/t/questions-to-the-output-of-fmriprep-distortion-correction-sdc/6295

**Comment by oesteban** [comment]
This is indeed an expected behavior. Whether the plot is improvable is a matter of discussion. Please reopen if you (or anyone) have immediate thoughts on how to make this plot less confusing.
